[mysql]
host = "br1068.hostgator.com.br" # Se falhar, use "69.49.241.31"
port = 3306
database = "meupat12_espiao_bucal"
user = "meupat12_espiaobucal" # Confirme se tem o prefixo "meupat12_"
password = "Helena@!*2026"